In [5]:
import torch

inputs=torch.tensor( # 6 tokens long sentence, each token is 3D embedding
    [[0.43,0.15,0.89],
     [0.55,0.87,0.66],
     [0.57,0.85,0.64],
     [0.22,0.58,0.33],
     [0.77,0.25,0.10],
     [0.05,0.80,0.55]]
)
query=inputs[1]
print(f"{query.shape=}")
attn_scores2=torch.matmul(inputs, query[:,None]).squeeze(-1)
print(f"{attn_scores2.shape=}\n{attn_scores2}")

query.shape=torch.Size([3])
attn_scores2.shape=torch.Size([6])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [11]:
attention=torch.matmul(inputs, inputs.T) # inputs @ inputs.T
print(f"{attention.shape}\n{attention}")
normalized_attention=attention/attention.sum(dim=1,keepdim=True)
print(f"{normalized_attention.shape}\n{normalized_attention}")

torch.Size([6, 6])
tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
torch.Size([6, 6])
tensor([[0.2241, 0.2140, 0.2113, 0.1066, 0.1026, 0.1415],
        [0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656],
        [0.1454, 0.2277, 0.2248, 0.1280, 0.1104, 0.1637],
        [0.1304, 0.2313, 0.2275, 0.1354, 0.0953, 0.1801],
        [0.1436, 0.2219, 0.2245, 0.1090, 0.2088, 0.0921],
        [0.1350, 0.2325, 0.2269, 0.1405, 0.0628, 0.2022]])


In [18]:
# each row i-th represents the attention of token i-th to other tokens in this sentence
soft_max_attention=torch.softmax(attention, dim=1) 
print(f"{soft_max_attention.shape=}\n{soft_max_attention}")
soft_max_attention.sum(dim=1)

soft_max_attention.shape=torch.Size([6, 6])
tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [16]:
query=inputs[1]
print(f"{query.shape=}\n{query}")
context_vec2=torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    print(i, f" {x_i.shape=}, {x_i}")
    context_vec2+=soft_max_attention[1,i]*x_i

print(f"\n{context_vec2=}")

query.shape=torch.Size([3])
tensor([0.5500, 0.8700, 0.6600])
0  x_i.shape=torch.Size([3]), tensor([0.4300, 0.1500, 0.8900])
1  x_i.shape=torch.Size([3]), tensor([0.5500, 0.8700, 0.6600])
2  x_i.shape=torch.Size([3]), tensor([0.5700, 0.8500, 0.6400])
3  x_i.shape=torch.Size([3]), tensor([0.2200, 0.5800, 0.3300])
4  x_i.shape=torch.Size([3]), tensor([0.7700, 0.2500, 0.1000])
5  x_i.shape=torch.Size([3]), tensor([0.0500, 0.8000, 0.5500])

context_vec2=tensor([0.4419, 0.6515, 0.5683])


In [17]:
# attention of each row i-th applied to all tokens in each embedding dimension
context_vectors=torch.matmul(soft_max_attention, inputs) # soft_max_attention @ inputs
print(f"{context_vectors.shape=}\n{context_vectors}")

context_vectors.shape=torch.Size([6, 3])
tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])
